<?php

namespace Jrk\Portfolio\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CountryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CountryRepository extends EntityRepository
{

    public function getCountriesIn($ids)
    {
        $sql = 'SELECT country FROM JrkPortfolioCoreBundle:Country country WHERE country.id in ('.$ids.')';
        $qba = $this->_em->createQuery($sql);
        return $qba->getResult();
    }

}
