imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

parameters:
    locales: [en,fr]
    required_locales: [en]
    email_from: 'portfolio@laposte.net'
    privileges_password: '123portfolio'
    privileges_encoder: 'sha512'
    translation:
        front_map: 'JrkPortfolioCoreBundle'

framework:
    #esi:             ~
    translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:
        name: 'portfolio_cookie'
        cookie_lifetime: 30879000 # 1 year
        cookie_httponly: false
    fragments:       ~

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    form:
        resources:
            - 'JrkPortfolioFrontBundle:Layout:form.html.twig'

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar
        #yui_css:
        #    jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: %kernel.root_dir%/data/data.db3
        # path:     %database_path%

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        entity_managers:
            default:
                auto_mapping: true
                filters:
                    oneLocale:
                        class: A2lix\I18nDoctrineBundle\Doctrine\ORM\Filter\OneLocaleFilter
                        enabled: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
#   spool:     { type: memory }


# Extensions
stof_doctrine_extensions:
    orm:
        default:
            sluggable: true
            timestampable: true

services:
    twig.extension.text:
       class: Twig_Extensions_Extension_Text
       tags:
           - { name: twig.extension }

    get_set_method_normalizer:
       class: Symfony\Component\Serializer\Normalizer\GetSetMethodNormalizer
       tags:
          - { name: serializer.normalizer }

# I18n stuff
jms_i18n_routing:
    default_locale: "%locale%"
    locales: "%locales%"
    strategy: prefix_except_default

lexik_translation:
    fallback_locale: "%locale%"  # (required) default locale to use
    managed_locales: "%locales%"

a2lix_i18n_doctrine:
    manager_registry: doctrine

a2lix_translation_form:
    locales: "%locales%"
    required_locales: "%required_locales%"
    manager_registry: doctrine
    templating: "JrkPortfolioBackBundle:Layout:a2lix-form-template.html.twig"

# Form features
genemu_form:
    select2: ~
    autocomplete: ~

# Rich text form
ivory_ck_editor:
    configs:
        basic_config:
            enterMode: CKEDITOR.ENTER_P
            shiftEnterMode: CKEDITOR.ENTER_P
            pasteFromWordRemoveStyles: false
            pasteFromWordRemoveFontStyles: false

# User management
fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Jrk\Portfolio\UserBundle\Entity\User
    service:
            mailer: fos_user.mailer.twig_swift
    resetting:
        token_ttl: 1
        email:
            from_email:
                address:        %email_from%
                sender_name:    Portfolio
        form:
            type:               fos_user_resetting
            name:               fos_user_resetting_form
            validation_groups:  [ResetPassword, Default]
    registration:
        confirmation:
            from_email:
                address:        %email_from%
                sender_name:    Portfolio
            enabled:    true
        form:
            type: jrk_portfolio_user_registration

# Photo dimension management
liip_imagine:
    resolvers:
        default:
            web_path:
                web_root: %kernel.root_dir%/../web
                cache_prefix: uploads/cache
    filter_sets:
        cache: ~
        x_small:
            filters:
                thumbnail: { size: [32, 32], mode: outbond }
        small:
            filters:
                thumbnail: { size: [64, 64], mode: outbond }
        medium:
            filters:
                thumbnail: { size: [100, 100], mode: outbond }
        large:
            filters:
                thumbnail: { size: [160, 160], mode: outbond }
        x_large:
            filters:
                thumbnail: { size: [280, 280], mode: outbond }
        project_cover:
            filters:
                thumbnail: { size: [650, 350], mode: outbound }

# Form captcha
gregwar_captcha: ~


# Mobile detection
mobile_detect:
    redirect:
        mobile: ~
        tablet: ~
    switch_device_view: ~