parameters:
#    jrk_portfolio_user.example.class: Jrk\Portfolio\UserBundle\Example

services:
#    jrk_portfolio_user.example:
#        class: %jrk_portfolio_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    jrk_portfolio_user.off_provider:
       class: Jrk\Portfolio\UserBundle\Security\Provider\CustomProvider
       public: false
       arguments: ["@fos_user.user_manager","@doctrine.orm.entity_manager"]

    off.login_form:
        class: Jrk\Portfolio\UserBundle\Services\LoginForm
        arguments: [%translation%,@request_stack,@service_container]
        tags:
             - { name: twig.extension }